### ISSUE TITLE
Gitlab and bitbucket support

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/translate.dokuwiki.org#114]
For these platforms similar libraries are available as we already use for GitHub.

https://github.com/BitbucketPHP/Client
https://github.com/GitLabPHP/Client

**Comment by Klap-in** [comment]
Who could help me with understand the (im)possibilities of Bitbucket?

For the GitHub and GitLab the Translation tool uses 'personal access tokens' to authenticate in the API, to fork projects etc. ([more info](https://github.com/dokufreaks/dokuwiki-translation/wiki/Git-interaction)). (maybe, in the future we to replace the 'classic token' of GitHub by one of the more recent approaches.)

For Bitbucket there are different options for authenticating: https://developer.atlassian.com/cloud/bitbucket/rest/intro/
 * repository access token (**free**, but useless because we need first to create the repository (=forking). So far I understand, I need for forking the `repository:write` permissions)
 * workspace access token (**payed**/premium feature)
 * project access token (**payed**/premium feature)
 * OAuth 2.0: with client-id the client(=Translation Tool) can authorize at Bitbucket. So far I saw it is **free**. However, in my understanding, that needs end user participation (=with our Translation tool user account) at the Bitbucket page for granting us the requested permissions. Then we get a code we can swap for the access token. If we have this access token it works similar as the personal access tokens (probably an implementing of a refresh of the access token is needed as well). For me the need for end user participation seems very unpractical for process mainly initiated by cronjobs. That would require an other interface for first time creating the AOuth access token.

My understanding is that OAuth is nice if we need multiple people to grant us access to their Bitbucket. But here it is granting our self the permissions for access via the api. 
- Is my interpretation right that I can use OAuth as alternative for workspace/project access tokens?
- do you see an alternative that is less work?
- or is the OAuth the future, and worth the effort to introduce also for GitHub/Gitlab?

**Comment by splitbrain** [comment]
Here's my understanding. If you want to implement Bitbucket Support in the way we support Github, we would create a user on bitbucket (dokuwiki-translate). We then would need to go through the oauth workflow with that user once (creating the token and refresh-token). From then on our application can work on behalf of that user. That should be enough to fork public repositories on bitbucket into the account of dokuwiki-translate and create pull requests from there. No interaction by the users running those repos needed.

However, I am not sure it's worth it. Have you checked how many plugins are actually hosted on bitbucket? TBH, I'd be fine with requiring github for the use of the translation tool.

**Comment by Klap-in** [comment]
I succeeded in implementing GitLab already.
There are not that many bitbucket repositories in use. About 15…

I meant that OAuth for bitbucket would be only needed for interaction via our user account of the translation tool. Not other users such as repos we fork, indeed.

As Bitbucket has the annoyance of payed personal access tokens, it make sense to skip it further due to the low usage.

**Comment by Klap-in** [comment]
GitLab support is implemented. Bitbucket is not doable due to payed tokens.
