### ISSUE TITLE
consolidate documentation

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/translate.dokuwiki.org#119]
Currently we have documentation at various places:

* [x] https://github.com/dokuwiki/translate.dokuwiki.org/blob/master/README.md
* [x] https://github.com/dokuwiki/translate.dokuwiki.org/blob/master/TODO
* [x] https://github.com/dokuwiki/translate.dokuwiki.org/wiki
* [x] https://www.dokuwiki.org/teams:translate-tool

This should be consolidated in one place (I think the github wiki is a good choice) and updated to reflect the current state.

**Comment by Klap-in** [comment]
Every thing moved to the GitHub wiki. Todos are now in the issue tracker.
