### ISSUE TITLE
Feature request:  Display 2nd language

### ISSUE THREAD

**Issue by jFMd21** [dokuwiki/translate.dokuwiki.org#95]
On the main translation page, where English and language to be translated are displayed in 2 columns, could we have a third column with another language there.

This would make translation of "dialects"  (e.g. like de and de-informal)  way easier and would enable to translate those dialects faster as one and therefore more consistent...

**Comment by Klap-in** [comment]
Unfortunately this is quite some work. Is a workaround maybe to open a second browser window with the other translation in the translation tool?
